###GET EQUIPOS
GET http://127.0.0.1:3000/equipos
Content-Type: application/json

###GET JUGADORES DE UN EQUIPO
GET http://127.0.0.1:3000/equipos/1/jugadores
Content-Type: application/json

###POST LOGIN
POST http://127.0.0.1:3000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
}

###POST REGISTRAR UN EQUIPO
POST http://127.0.0.1:3000/equipos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzE4Njg0NDkwfQ.t7Im61SPBpqlQ1RkWcF3g3YpVSqyhn7dah_r9WqSvVk

{
    "name": "FC Santiago Wanderers"
}

###POST REGISTRAR UN JUGADOR
POST http://127.0.0.1:3000/equipos/1/jugadores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzE4Njg0NDkwfQ.t7Im61SPBpqlQ1RkWcF3g3YpVSqyhn7dah_r9WqSvVk

{
    "name": "Arturo Vidal",
    "position": 2
}

###POST REGISTRAR UN USUARIO
POST http://127.0.0.1:3000/usuarios
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
}